### ISSUE TITLE
Entah kenapa 😓

### ISSUE THREAD

**Issue by ryugenxd** [Teams-of-Termux-Indonesia/ZhellServer#3]
![IMG_20220921_233353](https://user-images.githubusercontent.com/109148993/191547740-0f284f42-7860-4e4f-81ec-7b99000054a5.jpg)
**w sengaja ga gunakan variabel bro variabel ga bisa ke baca soal nya gw dah coba pertama buat tool nya**
@fiandev

**Comment by ryugenxd** [comment]
Ini yang gw cari tau

**Comment by Rezenxd** [comment]
Hdeh tulisan nya not found

**Comment by ryugenxd** [comment]
![IMG_20220922_000214](https://user-images.githubusercontent.com/109148993/191554397-bf416a9c-d31e-48ec-8b75-dcde374f4fc6.jpg)
Ok udah gw fix bug nya

**Comment by fiandev** [comment]
Kok bisa ga kebaca yah, harusnya bener kan syntax nya?

**Comment by ryugenxd** [comment]
Variabel lu masukin salah bro😂 mala pakai variabel php

**Comment by ryugenxd** [comment]
Fix bug
